# Tensorflow Demo

# Tensorflow 2 MNIST Demo

In [5]:
import tensorflow as tf

In [6]:
mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

Build model, choose an optimizer and the loss function

In [7]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

Looking at what the model is doing in terms of the outputs/vectors

In [8]:
pred = model(x_train[:1]).numpy()
pred

array([[-0.38371238, -0.02722132,  0.14302127,  0.13109547, -0.25615984,
        -0.5425336 ,  0.58408946,  0.5421132 ,  0.19191769,  0.0075238 ]],
      dtype=float32)

Probability of each class instead of the vectors

In [9]:
tf.nn.softmax(pred).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.06173841, 0.0881815 , 0.10454733, 0.10330793, 0.07013758,
        0.05267206, 0.16250488, 0.15582472, 0.10978637, 0.09129922]],
      dtype=float32)>>